version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=""

  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=notifier
      - MYSQL_USER=root
    ports:
      - 3306:3306
